# Generated by Django 4.2.5 on 2023-09-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='phone_number',
            field=models.IntegerField(default=15151515, max_length=15),
            preserve_default=False,
        ),
    ]
