# Generated by Django 4.2.2 on 2023-07-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام پرداخت')),
                ('amount', models.IntegerField(verbose_name='مقدار')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='تخفیف')),
            ],
            options={
                'verbose_name': 'پرداخت های فلو',
                'verbose_name_plural': 'پرداخت های فلو',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveBigIntegerField(verbose_name='مقدار')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=30, verbose_name='وضعیت')),
                ('transaction_id', models.CharField(max_length=200, verbose_name='آیدی تراکنش')),
            ],
            options={
                'verbose_name': 'تراکنش ها',
                'verbose_name_plural': 'تراکنش ها',
            },
        ),
        migrations.CreateModel(
            name='SystemExceptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('login_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کاربری کاربر')),
                ('file_path', models.CharField(blank=True, max_length=250, null=True, verbose_name='مسیر محل قرارگیری کد')),
                ('line_number', models.IntegerField(blank=True, null=True, verbose_name='شماره خط')),
                ('exception_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان خطا')),
                ('exception_content', models.TextField(verbose_name='محتوای خطا')),
                ('exact_info', models.TextField(blank=True, null=True, verbose_name='اطلاعات دقیق خطا')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'لاگ خطای سیستم',
                'verbose_name_plural': 'لاگ خطاهای سیستم',
            },
        ),
        migrations.CreateModel(
            name='TransactionAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='تومان')),
            ],
            options={
                'verbose_name': 'مقادیر پرداخت به کیف پول',
                'verbose_name_plural': 'مقادیر پرداخت به کیف پول',
            },
        ),
    ]
