# Generated by Django 4.2.5 on 2023-09-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0002_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='username',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
