# Generated by Django 4.2.5 on 2023-09-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0003_remove_payment_user_payment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='username',
        ),
        migrations.AddField(
            model_name='payment',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
